EBI ARCHIVE DOWNLOADER
jansen44/ebi-manga-reader pull request #1
Opened 2022-05-02 04:09 UTC by uasouz

2022-05-02 22:49 UTC, jansen44 requested changes

2022-05-02 22:49 UTC, jansen44 commented on ebi_sources/Cargo.toml
> +#path = "bin/main.rs"
```suggestion
[[bin]]
name = "bin_ebi_sources"
path = "bin/main.rs"
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/examples/opex.rs
> +    // }
```suggestion
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/errors.rs
> +        match *self {
```suggestion
        match self {
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/errors.rs
> +        match *self {
```suggestion
        match self {
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/errors.rs
> +            match *self {
```suggestion
            match self {
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/errors.rs
> +            match *self {
```suggestion
            match self {
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/downloader.rs
> +    };
I feel like create_directory could be a separated function

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/downloader.rs
> +    };
Either way, avoid panic: error propagation is your friend.
Everything thing could be simplified to:

```suggestion
    let _= fs::create_dir_all(format!(
        "{source_name}/{identifier}/{chapter}",
        source_name = "opex",
        identifier = manga_identifier,
        chapter = chapter_number
    ))?;
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/downloader.rs
> +}
It's generally a good idea to work with &str slices instead of owned Strings when dealing with parameters for some reasons (working with references, being possible to work with Strings, &str and literals with the same function, etc);

```suggestion
async fn download_page(page: &str, destination: &str) -> Result<(), DownloadError> {
    let resp = reqwest::get(page.to_owned()).await?;

    let mut out = File::create(destination.to_owned()).expect("failed to create file");
    let mut content = Cursor::new(resp.bytes().await?);
    io::copy(&mut content, &mut out).expect("failed to copy content");
    Ok(())
}
```

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/downloader.rs
> +        }));
It's good to avoid dealing with external variables when dealing with callback (specially when dealing with concurrency), a better approach would be to perform the clone inside the callback itself, but if you're adopting the &str change you can do something like this:

```suggestion
        tasks.push(tokio::spawn(async move {
            let downloaded = download_page(page.as_str(), destination).await;
            match downloaded {
                Err(err) => Err(DownloadError::GenericError(format!(
                    "ERROR downloading {}: {}",
                    page, err
                ))),
                _ => Ok(()),
            }
        }));
```

Since download_page would not take the ownership there's no reason to clone it anymore

2022-05-02 22:49 UTC, jansen44 commented on ebi_archive/lib/downloader.rs
> +}
Expect is also not that great, adding FileErrors to DownloadError enum and returning with a ? will make it cleaner and recoverable

2022-05-02 22:49 UTC, jansen44 commented on ebi_sources/Cargo.toml
> +#path = "bin/main.rs"
why??

2022-05-02 23:48 UTC, uasouz commented on ebi_archive/lib/errors.rs
> +        match *self {
what is the difference? a dereferencing?

2022-05-02 23:52 UTC, uasouz commented on ebi_archive/lib/downloader.rs
> +        }));
Which kind of problem this use of an external variable could cause?

2022-05-07 12:44 UTC, jansen44 approved these changes

2022-05-07 12:44 UTC, merged